import { cn } from "@/lib/utils";
import ReactLenis from "lenis/react";
import type { Metadata } from "next";
import "./globals.css";
import ActiveSectionContextProvider from "@/components/provider/active-section-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn("bg-[#f6f2e5] text-[#292929] relative overflow-x-hidden")}
      >
        <ReactLenis root>
          <ActiveSectionContextProvider>
            {children}
          </ActiveSectionContextProvider>
        </ReactLenis>
      </body>
    </html>
  );
}
